export const REGISTER = 'user/register/'
export const LOGIN = 'user/login/'
export const PERSONAL_INFO = 'user/personal_info/'
export const DIRECTORS = 'director/view/'
export const ADD_MOVIE = 'film/create/'
export const SEARCH_MOVIE = 'dsearch/SBert/'
export const RECOMMENDED_MOVIES = 'Recomender/view/'
export const REVIEW_MOVIE = 'review/create/'
